# Generated by Django 5.0.3 on 2024-03-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_id',
            field=models.CharField(default='0', max_length=100, unique=True),
        ),
    ]
